"""empty message

Revision ID: 5286a2e0694b
Revises: 
Create Date: 2017-12-15 14:49:34.635560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5286a2e0694b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_drink_id_fkey', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_username_fkey', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_username_fkey', 'favorites', 'users', ['username'], ['username'])
    op.create_foreign_key('favorites_drink_id_fkey', 'favorites', 'drinks', ['drink_id'], ['id'])
    op.drop_column('favorites', 'user_id')
    op.drop_column('favorites', 'id')
    # ### end Alembic commands ###
